apiVersion: v1
kind: Service
metadata:
  name: test-app-node-port
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8081
      nodePort: 30081
  type: NodePort
  